---
- name: upgrade all packages
  yum: name=* state=latest
  become: yes
  become_method: sudo

- name: install packages
  yum: name={{ item.package }} state=present
  become: yes
  become_method: sudo
  with_items: 
    - "{{ yum_packages }}"

