---
- name: zsh をインストール
  homebrew: name=zsh state=latest

- name: zsh のインストール情報保存先ディレクトリを作成
  file: path=brew_info state=directory

- name: zsh パッケージの情報を保存
  shell: /usr/local/bin/brew info zsh > brew_info/zsh

- name: set up zsh as default shell
  shell: /usr/bin/chsh -s '/bin/zsh' {{ ansible_env.USER }}
  become: yes

- name: cloning oh-my-zsh repository
  git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest={{ ansible_env.HOME }}/.oh-my-zsh
