---
- name: be sure zsh is installed
  apt: name=zsh state=present
  environment: proxy_env

- name: set up zsh as default shell
  command: chsh -s '/bin/zsh' {{ ansible_env.USER }}

- name: cloning oh-my-zsh repository
  git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest={{ ansible_env.HOME }}/.oh-my-zsh
