---
- name: tmux をインストール
  homebrew: name=tmux state=latest

- name: tmux インストール情報保存先ディレクトリを作成
  file: path=brew_info state=directory

- name: brew パッケージの情報を保存
  shell: /usr/local/bin/brew info tmux > brew_info/tmux
