---
- name: install the latest version of ruby
  yum: name=ruby state=latest

- name: check out rbenv int "~/.rbenv"
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv

- name: add "~/.rbenv/bin" to my $PATH
  shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.zshrc

- name: add "rbenv init" to my shell to enable shims and autocompletion
  shell: echo 'eval "$(rbenv init -)"' >> ~/.zshrc

- name: install as a rbenv plugin
  git: repo=https://github.com/rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build
