---
- name: set up my dotfiles
  git: repo=https://github.com/momota/dotfiles.git dest={{ ansible_env.HOME }}/dotfiles

- name: change .sh file mode
  file: path="{{ ansible_env.HOME }}/dotfiles/link_dotfiles.sh" mode=0755

- name: make symbolic link for dotfiles
  shell: "sh {{ ansible_env.HOME }}/dotfiles/link_dotfiles.sh"
